---
- name: 'STAGE 1: Prepare jumbox for OpenStack configuration'
  import_playbook: playbooks/1_prepare_jumpbox.yml
  tags:
    - stage1
    - prepare_workstation

- name: 'STAGE 2: Build OpenStack VPC'
  import_playbook: playbooks/2_build_osp_vpc.yml
  tags:
    - stage2
    - build_cloud
...
