---
- name: 'STAGE 1: Prepare jumbox for OpenStack configuration'
  import_playbook: playbooks/1_prepare_jumpbox.yml
  tags:
    - stage1
    - prepare_workstation

- name: 'STAGE 2: Deploy OpenStack VPC'
  import_playbook: playbooks/2_build_osp_vpc.yml
  tags:
    - stage2
    - deploy_vpc

- name: 'STAGE 3: Deploy OpenStack Instances'
  import_playbook: playbooks/3_build_osp_infrastructure.yml
  tags:
    - stage3
    - deploy_instances
...
